// scripts/authoring.ts
//
// Canonical seed arrays for Sabiqoo. Re-exported by `scripts/seed.ts` and
// `scripts/migrate.ts`, and unit-tested by `__tests__/seed.test.ts`.
//
// Field naming convention (snake_case) intentionally mirrors the SQL
// column names in `src/db/schema.ts` so the INSERT statements in
// `scripts/seed.ts` can spread these rows directly into prepared statements.

export type UnitRow = {
  id: number;
  title_en: string;
  title_ar: string;
  sort_order: number;
};

export type CategoryRow = {
  id: number;
  name_en: string;
  name_ar: string;
  icon_name: string;
  color_code: string;
  unit_id: number;
  sort_order: number;
};

export type DeedRow = {
  slug: string;
  category_id: number;
  unit_id: number;
  title_ar: string;
  title_en: string;
  description_ar: string;
  description_en: string;
  xp_reward: number;
  difficulty_level: number;
  branch_group: number;
  is_repeatable: number;
  sort_order: number;
};

export type ReferenceType = 'quran' | 'hadith' | 'athkar';

export type DeedReferenceRow = {
  deed_slug: string;
  type: ReferenceType;
  text_ar: string;
  text_en: string | null;
  source: string;
  narrator: string | null;
  lesson_ar: string | null;
  lesson_en: string | null;
  sort_order: number;
};

// Helper that returns a DeedRow with sensible defaults; callers override
// only the fields they care about (xp_reward, difficulty_level, branch_group,
// sort_order). Keeps the seed list readable without sacrificing typing.
function d(
  slug: string,
  categoryId: number,
  unitId: number,
  titleAr: string,
  titleEn: string,
  descriptionAr: string,
  descriptionEn: string,
  options: Partial<DeedRow> = {},
): DeedRow {
  return {
    slug,
    category_id: categoryId,
    unit_id: unitId,
    title_ar: titleAr,
    title_en: titleEn,
    description_ar: descriptionAr,
    description_en: descriptionEn,
    xp_reward: 10,
    difficulty_level: 1,
    branch_group: 1,
    is_repeatable: 1,
    sort_order: 1,
    ...options,
  };
}

// ---------------------------------------------------------------------------
// Units (8 total)
// ---------------------------------------------------------------------------

export const seedUnits: UnitRow[] = [
  {
    id: 1,
    title_en: 'Smile & Salam',
    title_ar: 'ابتسامة وسلام',
    sort_order: 1,
  },
  {
    id: 2,
    title_en: 'Kind Words',
    title_ar: 'كلمة طيبة',
    sort_order: 2,
  },
  {
    id: 3,
    title_en: 'Kinship Ties',
    title_ar: 'صلة الرحم',
    sort_order: 3,
  },
  {
    id: 4,
    title_en: 'Neighborly Acts',
    title_ar: 'خدمة الجار',
    sort_order: 4,
  },
  {
    id: 5,
    title_en: 'Animal Kindness',
    title_ar: 'الرفق بالحيوان',
    sort_order: 5,
  },
  {
    id: 6,
    title_en: 'Financial Charity',
    title_ar: 'الصدقات المالية',
    sort_order: 6,
  },
  {
    id: 7,
    title_en: 'Sadaqah Jariyah',
    title_ar: 'الصدقات الجارية',
    sort_order: 7,
  },
  {
    id: 8,
    title_en: 'Hands-on Service',
    title_ar: 'الأعمال الجسدية',
    sort_order: 8,
  },
];

// ---------------------------------------------------------------------------
// Categories (7 total)
// unit_id points to the "spirit" unit each category belongs to.
// ---------------------------------------------------------------------------

export const seedCategories: CategoryRow[] = [
  {
    id: 1,
    name_en: 'Financial Charity',
    name_ar: 'الصدقات المالية',
    icon_name: 'gift',
    color_code: '#58CC02',
    unit_id: 6,
    sort_order: 1,
  },
  {
    id: 2,
    name_en: 'Kinship & Family',
    name_ar: 'الأقارب والأرحام',
    icon_name: 'users',
    color_code: '#1CB0F6',
    unit_id: 3,
    sort_order: 2,
  },
  {
    id: 3,
    name_en: 'Sadaqah Jariyah',
    name_ar: 'الصدقات الجارية والأوقاف',
    icon_name: 'trending-up',
    color_code: '#CE82FF',
    unit_id: 7,
    sort_order: 3,
  },
  {
    id: 4,
    name_en: 'Physical Service',
    name_ar: 'الأعمال البدنية والتطوعية',
    icon_name: 'activity',
    color_code: '#FFC800',
    unit_id: 8,
    sort_order: 4,
  },
  {
    id: 5,
    name_en: 'Kind Words',
    name_ar: 'الكلمة الطيبة والمعنوية',
    icon_name: 'message-circle',
    color_code: '#FF4B4B',
    unit_id: 2,
    sort_order: 5,
  },
  {
    id: 6,
    name_en: 'Animals & Environment',
    name_ar: 'الرفق بالحيوان والبيئة',
    icon_name: 'heart',
    color_code: '#FF9600',
    unit_id: 5,
    sort_order: 6,
  },
  {
    id: 7,
    name_en: 'Relief & Sponsorship',
    name_ar: 'إغاثة وكفالة',
    icon_name: 'shield',
    color_code: '#2B70C9',
    unit_id: 8,
    sort_order: 7,
  },
];

// ---------------------------------------------------------------------------
// Deeds (~160 total, balanced across 7 categories)
// Helper `d()` above defines the default row. Difficulty ranges 1–3.
// branch_group=1 is the main path; branch_group=2 marks meaningful
// alternatives (e.g. financial ↔ non-monetary fallback, outdoor ↔ indoor).
// ---------------------------------------------------------------------------

export const seedDeeds: DeedRow[] = [
  // =========================================================================
  // UNIT 1 — Smile & Salam (unit_id=1, category 5 = words)
  // =========================================================================
  d(
    'smile-greet-stranger',
    5,
    1,
    'الابتسام في وجه الغريب',
    'Smile at a stranger',
    'الابتسامة صدقةٌ بسيطة، وقد تكون سببًا في تفريج كربة.',
    'A simple smile can uplift a stranger and is counted as charity.',
    { sort_order: 1 },
  ),
  d(
    'smile-someone-you-know',
    5,
    1,
    'الابتسام لمن تعرف',
    'Smile at someone you know',
    'الوجه البشوش يقرّب القلوب ويذهب الجفاء.',
    'A warm face brings hearts closer and removes coldness.',
    { sort_order: 2 },
  ),
  d(
    'say-salam-first',
    5,
    1,
    'بادر بإلقاء السلام',
    'Initiate with salam',
    'السلام اسمٌ من أسماء الله، فسلّموا بأحسن منه.',
    'Salam is one of Allah\u2019s names; greet one another with the best form of it.',
    { sort_order: 3 },
  ),
  d(
    'salam-to-family',
    5,
    1,
    'سَلِّم على أهلك عند الدخول',
    'Greet your family on entering',
    'يبدأ كثيرٌ من البيوت يومه بسلامٍ وبسمة.',
    'A good day in many homes begins with a smile and salam.',
    { sort_order: 4 },
  ),
  d(
    'salam-to-neighbor',
    5,
    1,
    'السلام على الجار',
    'Greet your neighbor',
    'السلام على الجار من حقوق الجوار في الإسلام.',
    'Greeting your neighbor is among the rights of neighbors in Islam.',
    { sort_order: 5 },
  ),
  d(
    'salam-to-elderly',
    5,
    1,
    'السلام على كبير السن',
    'Greet an elderly person',
    'إجلال الكبير من السنّة، والسلام عليه مفتاحُ بِرٍّ.',
    'Honoring elders is Sunnah; greeting them is a key to kindness.',
    { sort_order: 6 },
  ),
  d(
    'smile-at-sad-person',
    5,
    1,
    'ابتسم لمن تحزن حاله',
    'Smile at someone who looks sad',
    'ربّ ابتسامة تُسكِّن قلبًا مثقلًا.',
    'A single smile can soothe a heavy heart.',
    { sort_order: 7 },
  ),
  d(
    'wave-friendly-greeting',
    5,
    1,
    'لوِّح بيدك تحيةً',
    'Wave a friendly greeting',
    'إشارةٌ لطيفةٌ تعكس قلبًا حيًّا.',
    'A small gesture reflects a living heart.',
    { sort_order: 8 },
  ),
  d(
    'greet-shopkeeper-warmly',
    5,
    1,
    'حيِّ صاحب المتجر بابتسامة',
    'Greet the shopkeeper warmly',
    'السلام على من تتعامل معهم يفتح أبواب الرزق.',
    'Greeting those you deal with opens doors of provision.',
    { sort_order: 9 },
  ),
  d(
    'islamic-morning-greeting',
    5,
    1,
    'قُل صباحَ الخير بتحية الإسلام',
    'Say a cheerful Islamic morning greeting',
    'ابدأ يومك بالسلام تَجلب السكينة لنفسك ولمن حولك.',
    'Begin your day with salam; it brings calm to you and those around you.',
    { sort_order: 10 },
  ),
  d(
    'nod-smile-passersby',
    5,
    1,
    'أومئ بابتسامة للمارّة',
    'Nod with a smile to passers-by',
    'ما أبسطَ أثرَ الابتسامة في طريقك.',
    'How simple is the impact of a smile on your path.',
    { sort_order: 11 },
  ),
  d(
    'smile-in-mirror',
    5,
    1,
    'ابتسم لنفسك في المرآة',
    'Smile at yourself in the mirror',
    'الرضا بالنفس يبدأ بابتسامة صادقة.',
    'Self-acceptance begins with a sincere smile.',
    { sort_order: 12 },
  ),
  d(
    'welcome-newcomer',
    5,
    1,
    'رحّب بالوافد الجديد',
    'Welcome the newcomer',
    'كلمةٌ طيبةٌ تُنسيه وحشة المكان.',
    'A kind word eases the strangeness of a new place.',
    { sort_order: 13 },
  ),
  d(
    'gentle-eye-contact-smile',
    5,
    1,
    'ابتسامة ونظرة لطيفة',
    'A smile with gentle eye contact',
    'تواصلٌ صامتٌ يحمل معنى الاحترام.',
    'Silent eye contact carries the meaning of respect.',
    { sort_order: 14 },
  ),
  d(
    'greet-with-gesture',
    5,
    1,
    'السلام بإشارة لطيفة',
    'Greet with a kind gesture',
    'حين يعجز اللسان، يكفي القلب إشارةً.',
    'When words fall short, the heart speaks in gestures.',
    { sort_order: 15 },
  ),
  d(
    'smile-while-listening',
    5,
    1,
    'ابتسم وأنت تستمع',
    'Smile while you listen',
    'ابتسامة المستمع تُطمئن المتكلّم.',
    'A listener\u2019s smile reassures the speaker.',
    { sort_order: 16 },
  ),
  d(
    'friendly-nod-acknowledgement',
    5,
    1,
    'إيماءة ودٍّ',
    'A friendly nod of acknowledgement',
    'الموافقة الصامتة أبلغ من كثير كلام.',
    'Silent affirmation is more eloquent than many words.',
    { sort_order: 17 },
  ),
  d(
    'smile-while-serving',
    5,
    1,
    'ابتسم وأنت تخدم غيرك',
    'Smile while serving others',
    'العمل مع ابتسامةٍ أصدقُ من الوعد.',
    'Service with a smile is truer than a promise.',
    { sort_order: 18 },
  ),

  // =========================================================================
  // UNIT 2 — Kind Words (unit_id=2, category 5 = words)
  // =========================================================================
  d(
    'kind-words-to-spouse',
    5,
    2,
    'كلمة طيبة لزوجك أو زوجتك',
    'Kind words to your spouse',
    'الكلمة الحسنة للزوج أو الزوجة صدقةٌ لا تكلّف شيئًا.',
    'A kind word to your spouse is charity that costs nothing.',
    { sort_order: 1 },
  ),
  d(
    'thank-someone-today',
    5,
    2,
    'اشكر أحدًا اليوم',
    'Thank someone today',
    'الشكر لله بابٌ، وللخلق صلةٌ وودٌّ.',
    'Gratitude to Allah is a door; gratitude to people is connection.',
    { sort_order: 2 },
  ),
  d(
    'forgive-someone-today',
    5,
    2,
    'اغفر لأحدٍ اليوم',
    'Forgive someone today',
    'من أطلقَ سراحَ أخيه، أطلقَ اللهُ سراحَ قلبه.',
    'Whoever pardons his brother, Allah eases his own heart.',
    { sort_order: 3 },
  ),
  d(
    'excuse-someone-mistake',
    5,
    2,
    'اعذر أحدًا على زلّة',
    'Excuse someone\u2019s mistake',
    'العذرُ أيسرُ من العتاب، وأقربُ إلى المودّة.',
    'Pardon is easier than blame and closer to affection.',
    { sort_order: 4 },
  ),
  d(
    'kind-compliment-colleague',
    5,
    2,
    'مجاملة لطيفة لزميل',
    'A kind compliment to a colleague',
    'كلمةٌ طيبة تُحيي همّةً خامدة.',
    'A kind word revives a fading resolve.',
    { sort_order: 5 },
  ),
  d(
    'praise-good-deed',
    5,
    2,
    'امدح عملًا حسنًا',
    'Praise a good deed',
    'من لم يشكرِ الناسَ لم يشكرِ الله.',
    'He who thanks people has not thanked Allah.',
    { sort_order: 6 },
  ),
  d(
    'defend-absent-person',
    5,
    2,
    'دافع عن غائب في مجلس',
    'Defend someone absent',
    'ذُبَّ عن أخيك بالغيب يكن لك ناصرًا.',
    'Defend your brother in his absence; he will be your ally.',
    { sort_order: 7 },
  ),
  d(
    'reconcile-two-friends',
    5,
    2,
    'أصلح بين صديقين',
    'Reconcile two friends',
    'الإصلاح بين الناس أجرٌ عظيم.',
    'Reconciliation between people carries immense reward.',
    { sort_order: 8 },
  ),
  d(
    'gentle-advice',
    5,
    2,
    'انصح برفقٍ وعلم',
    'Offer gentle advice',
    'النصيحةُ بالرفق تُؤخذ، وبالغلظة تُردّ.',
    'Advice given gently is taken; given harshly, it is rejected.',
    { sort_order: 9 },
  ),
  d(
    'encouraging-words',
    5,
    2,
    'كلمات تشجيع صادقة',
    'Sincere words of encouragement',
    'كلمةٌ صادقة قد تغيّر مسارَ إنسان.',
    'A sincere word can change a person\u2019s course.',
    { sort_order: 10 },
  ),
  d(
    'words-of-consolation',
    5,
    2,
    'مواساة بكلمة',
    'Words of consolation',
    'ما يُعزّي القلبَ مثلُ كلمةٍ صادقة.',
    'Nothing consoles the heart like a sincere word.',
    { sort_order: 11 },
  ),
  d(
    'dua-for-someone-absent',
    5,
    2,
    'ادعُ لأحدٍ بظهر الغيب',
    'Make dua for someone in their absence',
    'دعوةُ الغيب تُستجاب بإذن الله.',
    'A dua made in someone\u2019s absence is answered, Allah willing.',
    { sort_order: 12 },
  ),
  d(
    'express-gratitude-aloud',
    5,
    2,
    'عبّر عن امتنانك بصوتٍ عالٍ',
    'Express your gratitude aloud',
    'الامتنان المعلَن يُعمِّق المودّة.',
    'Expressed gratitude deepens affection.',
    { sort_order: 13 },
  ),
  d(
    'compliment-parents-publicly',
    5,
    2,
    'أثنِ على والديك أمام الناس',
    'Compliment your parents publicly',
    'البرُّ كلمةٌ قبل أن يكون فعلًا.',
    'Honoring parents begins with words before deeds.',
    { sort_order: 14 },
  ),
  d(
    'congratulatory-message',
    5,
    2,
    'رسالة تهنئة',
    'A congratulatory message',
    'التهنئاتُ تُضاعف الفرح.',
    'Congratulations multiply joy.',
    { sort_order: 15 },
  ),
  d(
    'reply-kindly-message',
    5,
    2,
    'ردّ بلطفٍ على رسالة',
    'Reply kindly to a message',
    'اللطفُ في الردّ سجيةُ المؤمن.',
    'Kindness in replies is the nature of the believer.',
    { sort_order: 16 },
  ),
  d(
    'kind-words-to-upset-child',
    5,
    2,
    'كلمة لطيفة لطفل منزعج',
    'Kind words to an upset child',
    'القلبُ الصغير يحتاج كلمةً أكبر من الفعل.',
    'A small heart needs a word greater than an action.',
    { sort_order: 17 },
  ),
  d(
    'sincere-compliment',
    5,
    2,
    'مجاملة صادقة',
    'A sincere compliment',
    'الكلمة الصادقة صدقةٌ أيضًا.',
    'A truthful word is also charity.',
    { sort_order: 18 },
  ),

  // =========================================================================
  // UNIT 3 — Kinship Ties (unit_id=3, category 2 = kinship)
  // =========================================================================
  d(
    'call-parent-today',
    2,
    3,
    'اتصل بوالدك اليوم',
    'Call your parent today',
    'صلة الرحمُ لا تكلفُك إلا دقائق، وأثرها باقٍ.',
    'Maintaining kinship ties costs only minutes; their effect endures.',
    { sort_order: 1 },
  ),
  d(
    'visit-elderly-parent',
    2,
    3,
    'زر والديك المسنّين',
    'Visit your elderly parents',
    'الجلوسُ مع الوالدين عبادةٌ صامتة.',
    'Sitting with your parents is silent worship.',
    { sort_order: 2 },
  ),
  d(
    'send-gift-to-cousin',
    2,
    3,
    'أرسل هدية لابن عمّك',
    'Send a gift to a cousin',
    'الهديةُ تُجدّد الصلة وتُورث المودّة.',
    'A gift renews ties and deepens affection.',
    { sort_order: 3 },
  ),
  d(
    'forgive-family-member',
    2,
    3,
    'اغفر لأحد الأقارب',
    'Forgive a family member',
    'صلةُ الرحمِ تقتضي تجاوز الزلّات.',
    'Maintaining kinship ties requires overlooking faults.',
    { sort_order: 4 },
  ),
  d(
    'dua-for-deceased-relative',
    2,
    3,
    'ادعُ لميت من أقاربك',
    'Make dua for a deceased relative',
    'الصدقةُ والدعاء يصلان الميت.',
    'Charity and dua reach the deceased.',
    { sort_order: 5 },
  ),
  d(
    'reconnect-after-silence',
    2,
    3,
    'أعد التواصل بعد طول صمت',
    'Reconnect after a long silence',
    'لا يقطع الرحمَ إلا من لا يُقدّر نعمة الله في الأسرة.',
    'Only those ungrateful for family cut the ties of kinship.',
    { sort_order: 6 },
  ),
  d(
    'dua-for-parents',
    2,
    3,
    'ادعُ لوالديك',
    'Make dua for your parents',
    'ربِّ ارحمهما كما ربّياني صغيرًا.',
    'My Lord, have mercy on them as they raised me when I was small.',
    { sort_order: 7 },
  ),
  d(
    'visit-sick-relative',
    2,
    3,
    'عُد مريضًا من أقاربك',
    'Visit a sick relative',
    'عيادةُ المريض من حقوق المسلم، فكيف بالأقارب؟',
    'Visiting the sick is a right of a Muslim; how much more so of relatives.',
    { sort_order: 8 },
  ),
  d(
    'help-relative-with-work',
    2,
    3,
    'ساعد قريبًا في عمل',
    'Help a relative with work',
    'المعونةُ في العمل من صلة الرحم.',
    'Helping with work is part of maintaining kinship ties.',
    { sort_order: 9 },
  ),
  d(
    'surprise-family-gift',
    2,
    3,
    'فاجئ أهلك بهدية',
    'Surprise your family with a gift',
    'المفاجأة الصغيرة تُسعد القلب الكبير.',
    'A small surprise gladdens a great heart.',
    { sort_order: 10 },
  ),
  d(
    'share-meal-with-family',
    2,
    3,
    'شارك أهلك وجبة',
    'Share a meal with your family',
    'الأكل مع الأهل من سُنن الوصال.',
    'Eating with family is among the Sunnahs of bonding.',
    { sort_order: 11 },
  ),
  d(
    'babysit-nephew',
    2,
    3,
    'اعتنِ بابن أختك أو أخيك',
    'Babysit a nephew or niece',
    'خدمةُ الصغير رحمةٌ لأخته ومساعدةٌ لأخيك.',
    'Caring for a child is mercy to their mother and help to their parent.',
    { sort_order: 12 },
  ),
  d(
    'teach-cousin-skill',
    2,
    3,
    'علّم ابن عمّك مهارة',
    'Teach a cousin a skill',
    'العلمُ المُعطى للرحِم صدقة جارية.',
    'Knowledge given to relatives is ongoing charity.',
    { sort_order: 13 },
  ),
  d(
    'write-letter-to-elder',
    2,
    3,
    'اكتب رسالة لكبير العائلة',
    'Write to an elderly relative',
    'رسالةٌ تكتبها تُذكّرك بالدعاء، وتُفرح من يقرأها.',
    'A letter you write reminds you to make dua and gladdens its reader.',
    { sort_order: 14 },
  ),
  d(
    'check-in-on-aunt',
    2,
    3,
    'تفقّد خالتك أو عمّتك',
    'Check in on your aunt',
    'تفقّدُ الأقارب يُحيي الودّ ويمنعُ الجفاء.',
    'Checking on relatives revives affection and prevents coldness.',
    { sort_order: 15 },
  ),
  d(
    'help-sibling-errands',
    2,
    3,
    'ساعد أخاك في مشوار',
    'Help a sibling with errands',
    'ما من شيءٍ أحبّ إلى الله من مساعدة الأخ.',
    'Nothing is more beloved to Allah than helping a brother.',
    { sort_order: 16 },
  ),
  d(
    'read-quran-for-deceased-parent',
    2,
    3,
    'اقرأ القرآن لوالدك المتوفّى',
    'Recite Quran for your deceased parent',
    'يصلُ ثوابُ القرآن إلى الميت بإذن الله.',
    'The reward of Quran reaches the deceased, Allah willing.',
    { sort_order: 17 },
  ),
  d(
    'eid-greeting-family',
    2,
    3,
    'ابعت تهنئة العيد للأقارب',
    'Send Eid greetings to relatives',
    'تهنئةُ العيد تُحيي الصلة وتُجدّد المحبّة.',
    'Eid greetings revive ties and renew affection.',
    { sort_order: 18 },
  ),
  d(
    'host-family-gathering',
    2,
    3,
    'استضف الأقارب في بيتك',
    'Host a family gathering',
    'البيتُ الذي يجمعُ الأرحام مبارَك.',
    'A home that gathers relatives is blessed.',
    { sort_order: 19 },
  ),
  d(
    'reconcile-two-relatives',
    2,
    3,
    'أصلح بين أقارب متخاصمين',
    'Reconcile two feuding relatives',
    'الإصلاحُ بين الأهل من أفضل الأعمال.',
    'Reconciliation among family is among the best of deeds.',
    { sort_order: 20 },
  ),

  // =========================================================================
  // UNIT 4 — Neighborly Acts (unit_id=4)
  // Categories 4 (physical) + 7 (relief). branch_group=1 home help,
  // branch_group=2 community outreach.
  // =========================================================================
  d(
    'check-on-elderly-neighbor',
    4,
    4,
    'تفقّد جارك المسنّ',
    'Check on your elderly neighbor',
    'جسٌّ أو نبرةُ صوتٍ تُطمئن من ينتظر.',
    'A knock or a voice reassures one who is waiting.',
    { sort_order: 1 },
  ),
  d(
    'share-meal-with-neighbor',
    4,
    4,
    'شارك جارك طعامًا',
    'Share a meal with a neighbor',
    'إرسالُ طبقٍ إلى الجار من سنن الإسلام.',
    'Sending a dish to a neighbor is among the Sunnahs.',
    { sort_order: 2 },
  ),
  d(
    'help-neighbor-groceries',
    4,
    4,
    'ساعد جارك في حمل المشتريات',
    'Help a neighbor carry groceries',
    'يدٌ واحدةٌ ترفعُ حقيبتين، ويخفف اللهُ بها همًّا.',
    'One hand lifts two bags, and Allah lightens a worry through it.',
    { sort_order: 3 },
  ),
  d(
    'water-neighbor-plants',
    4,
    4,
    'اروِ نباتات جارك',
    'Water your neighbor\u2019s plants',
    'احفظ حديقة جارك كأنها حديقتك.',
    'Care for your neighbor\u2019s garden as if it were your own.',
    { sort_order: 4 },
  ),
  d(
    'bring-coffee-to-neighbor',
    4,
    4,
    'أحضر قهوة لجارك',
    'Bring coffee to a neighbor',
    'فنجانٌ واحدٌ يصنعُ ألفَ حديث.',
    'A single cup sparks a thousand conversations.',
    { sort_order: 5 },
  ),
  d(
    'check-on-sick-neighbor',
    4,
    4,
    'تفقّد جارك المريض',
    'Check on your sick neighbor',
    'عيادةُ الجار المريض من حقّ الجوار.',
    'Visiting a sick neighbor is a right of neighborhood.',
    { sort_order: 6 },
  ),
  d(
    'fix-something-for-neighbor',
    4,
    4,
    'أصلح شيئًا لجارك',
    'Fix something for a neighbor',
    'يدٌ صانعةٌ صدقةٌ عند الله.',
    'A working hand is charity before Allah.',
    { sort_order: 7, difficulty_level: 2 },
  ),
  d(
    'offer-help-moving',
    4,
    4,
    'اعرض المساعدة في نقل أثاث',
    'Offer to help with moving furniture',
    'النقلُ ثقيلٌ والأصحابُ كثير، فكن صاحبًا بحقّ.',
    'Moving is heavy and friends are many; be a true friend.',
    { sort_order: 8, difficulty_level: 2 },
  ),
  d(
    'share-recipe-neighbor',
    4,
    4,
    'شارك جارك وصفة',
    'Share a recipe with a neighbor',
    'الوصفةُ التي تُهدى تُطبخُ بركة.',
    'A gifted recipe is cooked with blessing.',
    { sort_order: 9 },
  ),
  d(
    'collect-neighbor-mail',
    4,
    4,
    'أحضر بريد جارك',
    'Collect your neighbor\u2019s mail',
    'ما لا يكلّفك إلا دقائقَ يُريح جارك أيامًا.',
    'What costs you minutes eases your neighbor for days.',
    { sort_order: 10 },
  ),
  d(
    'sweep-neighbor-sidewalk',
    4,
    4,
    'اكنس رصيف جارك',
    'Sweep your neighbor\u2019s sidewalk',
    'رصيفٌ نقيٌّ خيرٌ من شكوى الجار.',
    'A clean sidewalk is better than a neighbor\u2019s complaint.',
    { sort_order: 11 },
  ),
  d(
    'introduce-yourself-new-neighbor',
    7,
    4,
    'عرّف نفسك على جار جديد',
    'Introduce yourself to a new neighbor',
    'الترحيبُ أوّلُ جسرٍ بين بيتين.',
    'A welcome is the first bridge between two homes.',
    { sort_order: 12, branch_group: 2 },
  ),
  d(
    'lend-tool-neighbor',
    4,
    4,
    'أعر جارك أداة',
    'Lend a tool to a neighbor',
    'ما أغلى من أداةٍ يستفيد بها غيرك.',
    'How valuable is a tool that others benefit from.',
    { sort_order: 13, branch_group: 2 },
  ),
  d(
    'watch-neighbor-children',
    4,
    4,
    'راقب أطفال جارك قليلًا',
    'Watch a neighbor\u2019s children briefly',
    'دقائقٌ من المراقبة هديّةٌ لأمٍّ منهكة.',
    'Minutes of childcare are a gift to an exhausted mother.',
    { sort_order: 14, branch_group: 2 },
  ),
  d(
    'gift-fruit-to-neighbor',
    4,
    4,
    'أهدِ فاكهة لجارك',
    'Gift fruit to a neighbor',
    'طبقُ فاكهةٍ يُطفئُ غضبَ يوم.',
    'A plate of fruit cools a day\u2019s anger.',
    { sort_order: 15, branch_group: 2 },
  ),
  d(
    'visit-neighbor-on-eid',
    7,
    4,
    'عُد جارك في العيد',
    'Visit your neighbor on Eid',
    'عيدٌ بلا جيرانٍ عيدٌ ناقص.',
    'A celebration without neighbors is incomplete.',
    { sort_order: 16, branch_group: 2 },
  ),
  d(
    'help-neighbor-during-rain',
    4,
    4,
    'ساعد جارك عند هطول المطر',
    'Help a neighbor during heavy rain',
    'ما يُساقط المطرُ فيه من سقفٍ يُصلحه المسلم لوجه الله.',
    'A leak that the Muslim mends for Allah\u2019s sake is multiplied.',
    { sort_order: 17, branch_group: 2, difficulty_level: 2 },
  ),
  d(
    'invite-neighbor-iftar',
    7,
    4,
    'ادعُ جارك إلى الإفطار',
    'Invite a neighbor for iftar',
    'الجارُ إذا فطرَ عندك فكأنما صام يومًا في أجرك.',
    'When a neighbor breaks fast at yours, it is as if they fasted a day for you.',
    { sort_order: 18, branch_group: 2 },
  ),
  d(
    'cover-neighbor-rent',
    7,
    4,
    'ساعد جارك في دفع الإيجار',
    'Help a neighbor with rent',
    'ما أعظمَ أجرَ من وفّر بيتًا لأخيه.',
    'How great is the reward of one who provides a home for his brother.',
    { sort_order: 19, branch_group: 2, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'teach-neighbor-quran',
    7,
    4,
    'علّم جارك سورة من القرآن',
    'Teach your neighbor a surah',
    'خيركم من تعلّم القرآن وعلّمه.',
    'The best of you are those who learn the Quran and teach it.',
    { sort_order: 20, branch_group: 2 },
  ),
  d(
    'organize-neighborhood-cleanup',
    7,
    4,
    'نظّم حملة تنظيف الحيّ',
    'Organize a neighborhood cleanup',
    'حيٌّ نظيفٌ أثرُه يدومُ لأجيال.',
    'A clean neighborhood leaves a lasting legacy.',
    { sort_order: 21, branch_group: 2, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'cook-meal-for-sick-neighbor',
    7,
    4,
    'اطبخ وجبة لجارك المريض',
    'Cook a meal for a sick neighbor',
    'الطعامُ الطازج للمريض من أصدق صور الرحمة.',
    'Fresh food for the sick is among the truest forms of mercy.',
    { sort_order: 22, branch_group: 2 },
  ),

  // =========================================================================
  // UNIT 5 — Animal Kindness (unit_id=5, category 6 = animals)
  // branch_group=1 direct care, branch_group=2 environmental stewardship
  // =========================================================================
  d(
    'feed-stray-cat',
    6,
    5,
    'أطعم قطةً ضالة',
    'Feed a stray cat',
    'في كل كبدٍ رطبةٍ أجر.',
    'In every moist liver there is a reward.',
    { sort_order: 1 },
  ),
  d(
    'provide-water-for-bird',
    6,
    5,
    'ضع ماءً لعصفور',
    'Provide water for a bird',
    'وضعُ إناء ماءٍ للطيور صدقةٌ بسيطة.',
    'Placing a bowl of water for birds is simple charity.',
    { sort_order: 2 },
  ),
  d(
    'reduce-household-waste',
    6,
    5,
    'قلّل نفايات منزلك',
    'Reduce your household waste',
    'ما تُقلّلُه من هدرٍ هو ميراثٌ للأرض.',
    'What you reduce from waste is a legacy for the earth.',
    { sort_order: 3, branch_group: 2 },
  ),
  d(
    'recycle-materials',
    6,
    5,
    'أعد تدوير المواد',
    'Recycle materials',
    'تدويرُ الأشياء من شكر النعمة.',
    'Recycling is among the ways of thanking the blessing.',
    { sort_order: 4, branch_group: 2 },
  ),
  d(
    'plant-pollinator-flowers',
    6,
    5,
    'ازرع زهورًا محبّةً للنحل',
    'Plant pollinator-friendly flowers',
    'زهرةٌ واحدةٌ تكفي فراشةً.',
    'A single flower is enough for a butterfly.',
    { sort_order: 5, branch_group: 2 },
  ),
  d(
    'refill-bird-feeder',
    6,
    5,
    'أعد ملء وحدة تغذية الطيور',
    'Refill a bird feeder',
    'من يملأُ وحدةَ طعامٍ للطير فكأنما أطعم مسكينًا.',
    'One who fills a bird feeder is as if he fed a poor person.',
    { sort_order: 6 },
  ),
  d(
    'do-not-waste-food',
    6,
    5,
    'لا تُسرف في الطعام',
    'Don\u2019t waste food',
    'الإسرافُ في الطعام من الذنوب الخفيّة.',
    'Wasting food is among the hidden sins.',
    { sort_order: 7, branch_group: 2 },
  ),
  d(
    'water-for-ants-in-heat',
    6,
    5,
    'ضع ماءً للنمل في الحرّ',
    'Place water for ants in the heat',
    'الرحمةُ تمتدّ حتى أصغر المخلوقات.',
    'Mercy extends even to the smallest of creatures.',
    { sort_order: 8 },
  ),
  d(
    'avoid-disturbing-bird-nests',
    6,
    5,
    'لا تُزعج أعشاش الطيور',
    'Avoid disturbing bird nests',
    'من رأى عُشًّا فليَحفظه.',
    'Whoever sees a nest should protect it.',
    { sort_order: 9, branch_group: 2 },
  ),
  d(
    'adopt-from-shelter',
    6,
    5,
    'تبنَّ حيوانًا من ملجأ',
    'Adopt a pet from a shelter',
    'ما من حيوانٍ يُنقذُه الإنسان إلا شكره.',
    'No animal is saved by a human without being grateful.',
    { sort_order: 10, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'volunteer-at-animal-shelter',
    6,
    5,
    'تطوّع في ملجأ حيوانات',
    'Volunteer at an animal shelter',
    'ساعةٌ مع حيوانٍ محتاجٍ تَفتحُ قلبك.',
    'An hour with a needy animal opens your heart.',
    { sort_order: 11, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'donate-to-animal-welfare',
    6,
    5,
    'تبرّع لمنظمة رعاية حيوانات',
    'Donate to an animal welfare organization',
    'كلُّ ريالٍ للحيوانِ يحسبُه اللهُ صدقة.',
    'Every riyal for animals is counted as charity.',
    { sort_order: 12, branch_group: 2 },
  ),
  d(
    'care-for-sick-pet',
    6,
    5,
    'اعتنِ بحيوانك المريض',
    'Care for your sick pet',
    'من أعظم الوفاء أن ترعى حيوانًا في مرضه.',
    'Among the greatest loyalties is caring for a pet when it is sick.',
    { sort_order: 13, difficulty_level: 2 },
  ),
  d(
    'shelter-a-stray',
    6,
    5,
    'أَوِ ضالّةً ليلةً',
    'Shelter a stray animal for a night',
    'ليلةُ أمانٍ لحيوانٍ أجرٌ عند الله.',
    'A night of safety for an animal carries reward with Allah.',
    { sort_order: 14, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'plant-a-tree-shade',
    6,
    5,
    'ازرع شجرة للظلّ',
    'Plant a tree for shade',
    'ما من مسلمٍ يغرسُ شجرةً إلا كان له أجرٌ فيها.',
    'No Muslim plants a tree without receiving reward for it.',
    { sort_order: 15, branch_group: 2 },
  ),
  d(
    'use-reusable-bags',
    6,
    5,
    'استخدم أكياسًا قابلة لإعادة الاستخدام',
    'Use reusable bags',
    'كيسٌ واحدٌ أقلُّ يعني محيطًا أنظف.',
    'One bag less means a cleaner ocean.',
    { sort_order: 16, branch_group: 2 },
  ),
  d(
    'avoid-single-use-plastic',
    6,
    5,
    'تجنّب البلاستيك ذي الاستخدام الواحد',
    'Avoid single-use plastics',
    'كلُّ عبوةٍ تُكرّرها صدقةٌ للأرض.',
    'Every bottle you reuse is charity for the earth.',
    { sort_order: 17, branch_group: 2 },
  ),
  d(
    'compost-food-waste',
    6,
    5,
    'حوّل بقايا الطعام إلى سماد',
    'Compost food waste',
    'ما يُلقى يُحيا، وما يُدفن يُنعِم.',
    'What is thrown nourishes, what is buried enriches.',
    { sort_order: 18, branch_group: 2, difficulty_level: 2 },
  ),
  d(
    'save-bee-from-water',
    6,
    5,
    'أنقذ نحلةً من الماء',
    'Save a bee from water',
    'حياةُ نحلةٍ واحدةٍ تكلّفُك ثانيةً واحدة.',
    'Saving a single bee costs you a single second.',
    { sort_order: 19 },
  ),
  d(
    'build-a-birdhouse',
    6,
    5,
    'ابنِ بيتًا للطيور',
    'Build a birdhouse',
    'بيتٌ صغيرٌ للطيور يُفرح قلبَك أيامًا.',
    'A small birdhouse gladdens your heart for days.',
    { sort_order: 20, branch_group: 2, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'choose-cruelty-free-products',
    6,
    5,
    'اختر منتجات غير مُجرَّبة على الحيوانات',
    'Choose cruelty-free products',
    'اختيارُك الواعي يُحدث فرقًا في السوق.',
    'Your conscious choice makes a difference in the market.',
    { sort_order: 21, branch_group: 2 },
  ),
  d(
    'plant-herbs-at-home',
    6,
    5,
    'ازرع أعشابًا في بيتك',
    'Plant herbs at home',
    'أصيصٌ على النافذة بدايةُ جنتك.',
    'A pot on the windowsill is the start of your garden.',
    { sort_order: 22, branch_group: 2 },
  ),

  // =========================================================================
  // UNIT 6 — Financial Charity (unit_id=6, category 1 = financial)
  // branch_group=1 monetary, branch_group=2 non-monetary fallback
  // =========================================================================
  d(
    'give-charity-today',
    1,
    6,
    'تصدّق اليوم ولو بالقليل',
    'Give charity today',
    'تصدّق ولو بتمرة، فالحسابُ عند الله.',
    'Give charity even if it is a date; the reckoning is with Allah.',
    { sort_order: 1 },
  ),
  d(
    'buy-meal-for-worker',
    1,
    6,
    'اشترِ وجبةً لعامل',
    'Buy a meal for a worker',
    'وجبةٌ لعاملٍ دعوةٌ له بالرزق.',
    'A meal for a worker is a dua of provision for him.',
    { sort_order: 2 },
  ),
  d(
    'donate-clothing',
    1,
    6,
    'تصدّق بملابس مستعملة بحالة جيدة',
    'Donate gently-used clothing',
    'من فرّجَ كربةَ أخيه فرّجَ اللهُ كربَه.',
    'Whoever eases his brother\u2019s hardship, Allah eases his own.',
    { sort_order: 3 },
  ),
  d(
    'contribute-medicine-fund',
    1,
    6,
    'ساهم في دواء مريض',
    'Contribute to a sick person\u2019s medicine',
    'من أنقذ نفسًا فكأنما أنقذ الناس جميعًا.',
    'Whoever saves a life, it is as if he saved all of mankind.',
    { sort_order: 4, branch_group: 2, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'help-pay-debt',
    1,
    6,
    'ساعد في سداد دَين',
    'Help pay a debtor\u2019s debt',
    'من فُكَّتْ كربتُه في الدنيا فُكَّت عنه يوم القيامة.',
    'Whoever has his difficulty eased in this world, Allah will ease it on the Day of Judgment.',
    { sort_order: 5, branch_group: 2, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'sponsor-orphan-monthly',
    1,
    6,
    'كفّل يتيما شهريًا',
    'Sponsor an orphan monthly',
    'كافلُ اليتيم مع النبيّ في الجنّة.',
    'The guardian of an orphan will be with the Prophet in Paradise.',
    { sort_order: 6, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'round-up-savings',
    1,
    6,
    'قرّب مدّخراتك إلى رقمٍ أعلى',
    'Round up your savings for sadaqah',
    'حتى البقشيش الصغير يصبحُ صدقةً كبيرة.',
    'Even a small round-up becomes great charity.',
    { sort_order: 7, branch_group: 2 },
  ),
  d(
    'pay-for-strangers-coffee',
    1,
    6,
    'ادفع قيمة قهوة عن غريب',
    'Pay for a stranger\u2019s coffee',
    'كوبٌ واحدٌ قد يُغيّر يومَ إنسان.',
    'A single cup can change someone\u2019s day.',
    { sort_order: 8, branch_group: 2 },
  ),
  d(
    'give-with-dignity',
    1,
    6,
    'تصدّق على متسوّلٍ بكرامة',
    'Give to a beggar with dignity',
    'لا تُحرج السائلَ، فالعطاءُ قبل المال.',
    'Do not embarrass the asker; dignity comes before money.',
    { sort_order: 9 },
  ),
  d(
    'tip-delivery-generously',
    1,
    6,
    'أكرم ساعي التوصيل',
    'Tip the delivery person generously',
    'ما تنفقهُ في طيب الكسب أكثرُ بركة.',
    'What you spend in lawful earning is more blessed.',
    { sort_order: 10, branch_group: 2 },
  ),
  d(
    'buy-groceries-for-someone',
    1,
    6,
    'اشترِ حاجات أساسية لأحد',
    'Buy groceries for someone in need',
    'النفقةُ على الأهل والأقارب صدقة.',
    'Spending on family and relatives is charity.',
    { sort_order: 11, branch_group: 2 },
  ),
  d(
    'cover-colleague-lunch',
    1,
    6,
    'ادفع غداء زميل',
    'Cover a colleague\u2019s lunch',
    'من أطعمَ مؤمنًا أطعمَه اللهُ من ثمار الجنة.',
    'Whoever feeds a believer, Allah feeds him from the fruits of Paradise.',
    { sort_order: 12 },
  ),
  d(
    'fund-student-books',
    1,
    6,
    'ساعد طالبًا في شراء الكتب',
    'Help a student buy books',
    'من سلكَ طريقًا يلتمسُ فيه علمًا سهّلَ اللهُ له به طريقًا إلى الجنّة.',
    'Whoever takes a path to seek knowledge, Allah eases his path to Paradise.',
    { sort_order: 13, branch_group: 2, difficulty_level: 2 },
  ),
  d(
    'gift-newlywed-small',
    1,
    6,
    'أهدِ مبلغًا لعروسين',
    'Gift a small amount to a new marriage',
    'اللهُ في عون العبد ما كان العبدُ في عون أخيه.',
    'Allah is in the service of His servant as long as the servant is in service to others.',
    { sort_order: 14, branch_group: 2 },
  ),
  d(
    'contribute-funeral-expense',
    1,
    6,
    'ساهم في تكاليف جنازة',
    'Contribute to a funeral expense',
    'تخفيفُ العبء عن أهل الميت صدقةٌ عظيمة.',
    'Lightening the burden on a deceased\u2019s family is great charity.',
    { sort_order: 15, branch_group: 2, difficulty_level: 2 },
  ),
  d(
    'give-water-to-traveler',
    1,
    6,
    'اسقِ مسافرًا',
    'Give water to a traveler',
    'السقيا من أعظم أبواب الصدقة.',
    'Providing water is among the greatest doors of charity.',
    { sort_order: 16, branch_group: 2 },
  ),
  d(
    'pay-it-forward-grocery',
    1,
    6,
    'ادفع الفاتورة لمن خلفك في الصفّ',
    'Pay it forward at the grocery',
    'صدقةُ السرِّ تطفئ غضبَ الربّ.',
    'Hidden charity extinguishes the Lord\u2019s anger.',
    { sort_order: 17, branch_group: 2 },
  ),
  d(
    'donate-to-mosque',
    1,
    6,
    'تصدّق لصيانة مسجد',
    'Donate to mosque maintenance',
    'من بنى لله مسجدًا بنى اللهُ له بيتًا في الجنّة.',
    'Whoever builds a mosque for Allah, Allah builds him a house in Paradise.',
    { sort_order: 18 },
  ),
  d(
    'support-ramadan-family',
    1,
    6,
    'ادعم أسرةً في رمضان',
    'Support a family in Ramadan',
    'من فطّر صائمًا فله مثلُ أجره.',
    'Whoever feeds a fasting person gets the reward of fasting.',
    { sort_order: 19, branch_group: 2, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'cover-medical-bill',
    1,
    6,
    'ادفع فاتورة علاج محتاج',
    'Cover a medical bill for someone in need',
    'شفاءُ المرضى من دعوة صادقةٍ وعملٍ مبارَك.',
    'The healing of the sick comes from sincere dua and blessed action.',
    { sort_order: 20, branch_group: 2, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'sponsor-iftar',
    1,
    6,
    'كفّل إفطار صائم',
    'Sponsor an iftar',
    'من فطّر صائمًا كان له مثلُ أجره.',
    'Whoever provides iftar for a fasting person gets the like of their reward.',
    { sort_order: 21, branch_group: 2, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'pay-zakat-today',
    1,
    6,
    'أدّ زكاةَ مالك',
    'Pay your zakat today',
    'الزكاةُ طُهرةٌ للمال وتزكيةٌ للنفس.',
    'Zakat purifies wealth and refines the soul.',
    { sort_order: 22, difficulty_level: 2, xp_reward: 20 },
  ),

  // =========================================================================
  // UNIT 7 — Sadaqah Jariyah (unit_id=7, category 3 = jariyah)
  // branch_group=1 larger projects, branch_group=2 small sustainable acts
  // =========================================================================
  d(
    'plant-a-tree',
    3,
    7,
    'ازرع شجرة',
    'Plant a tree',
    'ما من مسلمٍ يغرسُ شجرةً إلا كان له أجرٌ فيها.',
    'No Muslim plants a tree without receiving ongoing reward for it.',
    { sort_order: 1 },
  ),
  d(
    'sponsor-quran-print',
    3,
    7,
    'كفّل طباعة مصحف',
    'Sponsor a Quran print',
    'صدقةُ العلم أبقى من صدقة المال.',
    'Charity of knowledge outlasts charity of money.',
    { sort_order: 2, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'donate-well-digging',
    3,
    7,
    'تبرّع لحفر بئر',
    'Donate to well-digging',
    'ما سقى اللهُ به نفسًا كان لصاحبه أجرُها.',
    'Whichever soul Allah quenches through you, you receive its reward.',
    { sort_order: 3, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'sponsor-student-education',
    3,
    7,
    'كفّل طالبًا في دراسته',
    'Sponsor a student\u2019s education',
    'من علّم آيةً كان له أجرُها إلى يوم القيامة.',
    'Whoever teaches a verse, its reward continues until the Day of Judgment.',
    { sort_order: 4, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'contribute-mosque-build',
    3,
    7,
    'ساهم في بناء مسجد',
    'Contribute to a mosque build',
    'من بنى لله مسجدًا بنى اللهُ له بيتًا في الجنّة.',
    'Whoever builds a mosque for Allah, Allah builds him a house in Paradise.',
    { sort_order: 5, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'teach-someone-quran',
    3,
    7,
    'علّم أحدًا قراءة القرآن',
    'Teach someone to recite the Quran',
    'خيركم من تعلّم القرآن وعلّمه.',
    'The best of you are those who learn the Quran and teach it.',
    { sort_order: 6 },
  ),
  d(
    'build-water-fountain',
    3,
    7,
    'ابنِ نافورة ماء عامّة',
    'Build a public water fountain',
    'السقيا صدقةٌ لكلّ من يشرب منها.',
    'Providing water is charity for every drinker.',
    { sort_order: 7, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'fund-islamic-school',
    3,
    7,
    'ادعم مدرسة إسلامية',
    'Fund an Islamic school',
    'من بنى لله بنيانًا كتب اللهُ له بكل حرفٍ حسنة.',
    'Whoever builds something for Allah, Allah records a good deed for each letter.',
    { sort_order: 8, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'print-islamic-literature',
    3,
    7,
    'اطبع كتيّبًا إسلاميًا',
    'Print Islamic literature',
    'كلمةٌ مكتوبةٌ تبقى بعدك.',
    'A written word outlives you.',
    { sort_order: 9, branch_group: 2 },
  ),
  d(
    'donate-land-cemetery',
    3,
    7,
    'وهب أرضًا لمقبرة',
    'Donate land for a cemetery',
    'الوقفُ صدقة جارية ما دام ينتفع به.',
    'An endowment is ongoing charity as long as it is used.',
    { sort_order: 10, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'build-public-library',
    3,
    7,
    'ادعم مكتبة عامة',
    'Support a public library',
    'كتابٌ واحدٌ قد يُغيّر حياة قارئ.',
    'A single book can change a reader\u2019s life.',
    { sort_order: 11, branch_group: 2 },
  ),
  d(
    'fund-hospital-wing',
    3,
    7,
    'تبرّع لقسم في مستشفى',
    'Fund a hospital wing',
    'شفاءُ الناس أجرٌ دائم.',
    'Healing people is ongoing reward.',
    { sort_order: 12, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'plant-date-palm',
    3,
    7,
    'ازرع نخلة',
    'Plant a date palm',
    'ما من مسلمٍ يغرسُ نخلةً إلا كان له أجرٌ كلّما أُكل منها.',
    'No Muslim plants a date palm without reward every time its fruit is eaten.',
    { sort_order: 13 },
  ),
  d(
    'create-online-islamic-resource',
    3,
    7,
    'أنشئ موردًا إسلاميًا على الإنترنت',
    'Create an online Islamic resource',
    'من دلّ على خيرٍ فله مثلُ أجر فاعله.',
    'Whoever guides to good receives the like of the doer\u2019s reward.',
    { sort_order: 14, branch_group: 2, difficulty_level: 2 },
  ),
  d(
    'share-free-skill-online',
    3,
    7,
    'شارك مهارة مجّانًا',
    'Share a free skill online',
    'كلُّ علمٍ تُعلّمه مجانًا يبقى أثرُه.',
    'Every skill you teach freely leaves a lasting impact.',
    { sort_order: 15, branch_group: 2 },
  ),
  d(
    'build-small-business-for-someone',
    3,
    7,
    'ساعد في إنشاء مشروع صغير',
    'Help build a small business for someone',
    'من أعان على صناعة الرزق كتبَ اللهُ له أجرَ المتصدّقين.',
    'Whoever helps provide for others is rewarded as a giver of charity.',
    { sort_order: 16, branch_group: 2, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'fund-a-teacher',
    3,
    7,
    'ادعم معلّمًا بمكافأة',
    'Fund a teacher with a stipend',
    'من كفى مؤمنًا مؤونته كلّفَه اللهُ القيامَ يوم القيامة.',
    'Whoever suffices a believer\u2019s needs, Allah will suffice him on the Day of Judgment.',
    { sort_order: 17, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'donate-books-to-school',
    3,
    7,
    'أهدِ كتبًا لمدرسة',
    'Donate books to a school',
    'من سنّ سنّةً حسنةً فله أجرُها وأجرُ من عمل بها.',
    'Whoever initiates a good tradition gets its reward and the reward of those who follow it.',
    { sort_order: 18, branch_group: 2 },
  ),
  d(
    'build-community-center',
    3,
    7,
    'ساهم في بناء مركز مجتمعي',
    'Contribute to a community center',
    'بناءُ المجتمع بناءٌ لنفسك.',
    'Building a community is building yourself.',
    { sort_order: 19, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'install-solar-lights',
    3,
    7,
    'ثبّت إنارة شمسية في قرية',
    'Install solar lights in a village',
    'العلمُ يُضيء والعلمُ نورٌ للأرض.',
    'Light on earth is light for its people.',
    { sort_order: 20, branch_group: 2, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'sponsor-quran-teacher',
    3,
    7,
    'ادعم معلّم قرآن',
    'Sponsor a Quran teacher',
    'من علّم آيةً كان له أجرُها وأجرُ من تعلّمها.',
    'Whoever teaches a verse gets its reward and the reward of those who learn it.',
    { sort_order: 21, branch_group: 2, difficulty_level: 2 },
  ),
  d(
    'sponsor-foundation-lessons',
    3,
    7,
    'ادعم دروس علمية',
    'Sponsor foundation lessons',
    'العلمُ ميراثُ الأنبياء.',
    'Knowledge is the inheritance of the prophets.',
    { sort_order: 22, branch_group: 2, difficulty_level: 2 },
  ),

  // =========================================================================
  // UNIT 8 — Hands-on Service (unit_id=8)
  // Categories 4 (physical) + 7 (relief). branch_group=1 outdoor/community,
  // branch_group=2 indoor / can-do-at-home fallback.
  // =========================================================================
  d(
    'remove-harm-from-path',
    4,
    8,
    'أزل أذى من الطريق',
    'Remove harm from the path',
    'إماطةُ الأذى عن الطريق صدقة.',
    'Removing harm from the path is charity.',
    { sort_order: 1 },
  ),
  d(
    'help-elderly-cross-street',
    4,
    8,
    'ساعد مسنًا في عبور الشارع',
    'Help an elderly person cross the street',
    'يدٌ تُمسك يدًا في الشارع تكتبُ لك حسنة.',
    'A hand holding another across the street records a good deed for you.',
    { sort_order: 2 },
  ),
  d(
    'visit-the-sick',
    4,
    8,
    'عُد مريضًا',
    'Visit the sick',
    'عيادةُ المريض حقٌّ من حقوق المسلم.',
    'Visiting the sick is a right of a Muslim.',
    { sort_order: 3 },
  ),
  d(
    'donate-blood',
    4,
    8,
    'تبرّع بدمك',
    'Donate blood',
    'من أنقذ نفسًا فكأنما أنقذ الناس جميعًا.',
    'Whoever saves a life, it is as if he saved all of mankind.',
    { sort_order: 4, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'clean-a-mosque',
    4,
    8,
    'نظّف مسجدًا',
    'Clean a mosque',
    'كنسُ المسجدِ من الأعمال التي يُبنى بها بيتٌ في الجنّة.',
    'Sweeping a mosque is among the deeds that build a house in Paradise.',
    { sort_order: 5, branch_group: 2 },
  ),
  d(
    'carry-shopping-bags',
    4,
    8,
    'احمل حقائب تسوّق',
    'Carry shopping bags for someone',
    'ما لا يُكلّفُك إلا دقائق يُريح غيرَك.',
    'What costs you minutes eases another\u2019s burden.',
    { sort_order: 6 },
  ),
  d(
    'open-door-for-someone',
    4,
    8,
    'افتح الباب لأحد',
    'Open the door for someone',
    'أبسطُ الأفعال قد يكونُ أثقلَها في الميزان.',
    'The simplest deeds may be the heaviest on the scale.',
    { sort_order: 7 },
  ),
  d(
    'give-up-your-seat',
    4,
    8,
    'تنازل عن مقعدك',
    'Give up your seat',
    'تنازلُك عن مقعدك يَزيدُ كرمًا عند الله.',
    'Giving up your seat increases you in generosity with Allah.',
    { sort_order: 8 },
  ),
  d(
    'help-with-directions',
    4,
    8,
    'دلّ تائهًا على الطريق',
    'Help a lost person with directions',
    'دلالةُ الخيرِ من الإيمان.',
    'Guiding to good is part of faith.',
    { sort_order: 9 },
  ),
  d(
    'volunteer-at-food-bank',
    4,
    8,
    'تطوّع في بنك طعام',
    'Volunteer at a food bank',
    'ساعةٌ تطوّعٍ تعادلُ شهرًا من الأثر.',
    'An hour of volunteering equals a month of impact.',
    { sort_order: 10, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'cook-for-neighbor',
    4,
    8,
    'اطبخ لجارك',
    'Cook for a neighbor',
    'طبَخُك لجارك أطيبُ من طبخك لنفسك.',
    'Your cooking for a neighbor is better than your cooking for yourself.',
    { sort_order: 11, branch_group: 2 },
  ),
  d(
    'mow-elderly-lawn',
    4,
    8,
    'احصد العشب لجار مسنّ',
    'Mow an elderly neighbor\u2019s lawn',
    'ما لا يستطيعُه الكبيرُ يستطيعُه الصغير.',
    'What the elder cannot do, the younger can do.',
    { sort_order: 12, branch_group: 2 },
  ),
  d(
    'volunteer-soup-kitchen',
    4,
    8,
    'تطوّع في مطبخ خيري',
    'Volunteer at a soup kitchen',
    'إطعامُ الطعام من أعظم الصدقات.',
    'Feeding others is among the greatest forms of charity.',
    { sort_order: 13, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'clean-public-park',
    4,
    8,
    'نظّف متنزّهًا عامًّا',
    'Clean a public park',
    'النظافةُ من الإيمان.',
    'Cleanliness is part of faith.',
    { sort_order: 14 },
  ),
  d(
    'distribute-water-in-heat',
    4,
    8,
    'وزّع ماءً في الحرّ',
    'Distribute water in the heat',
    'السقيا صدقةٌ في الحرّ يوم القيامة.',
    'Providing water is charity on a hot day of Judgment.',
    { sort_order: 15, branch_group: 2 },
  ),
  d(
    'serve-at-hospital',
    4,
    8,
    'اخدم في مستشفى',
    'Serve at a hospital',
    'ما من مريضٍ يُزارُ إلا ويُؤجَرُ الزائر.',
    'No sick person is visited without the visitor being rewarded.',
    { sort_order: 16, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'help-orphan-with-homework',
    7,
    8,
    'ساعد يتيمًا في الواجب',
    'Help an orphan with homework',
    'خيرُ البيوتِ بيتٌ يُرعى فيه يتيم.',
    'The best of homes is one where an orphan is cared for.',
    { sort_order: 17, branch_group: 2 },
  ),
  d(
    'sponsor-orphan-education',
    7,
    8,
    'كفّل تعليم يتيم',
    'Sponsor an orphan\u2019s education',
    'أنا وكافلُ اليتيم في الجنّة هكذا.',
    'I and the guardian of an orphan will be in Paradise like this.',
    { sort_order: 18, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'donate-to-disaster-relief',
    7,
    8,
    'تبرّع لإغاثة منكوبين',
    'Donate to disaster relief',
    'من فرّجَ عن مسلمٍ كربةً فرّجَ اللهُ عنه كربةً.',
    'Whoever relieves a Muslim\u2019s distress, Allah relieves his.',
    { sort_order: 19, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'help-refugee-with-supplies',
    7,
    8,
    'ساعد لاجئًا بمستلزمات',
    'Help a refugee with supplies',
    'اللاجئُ ضيفُ الأمّة.',
    'A refugee is a guest of the Ummah.',
    { sort_order: 20, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'pay-utility-bill-someone',
    7,
    8,
    'ادفع فاتورة خدمات لأسرة',
    'Pay a utility bill for a struggling family',
    'من أسدى إلى أهل بيتٍ معروفًا استحقّ أجرَهم.',
    'Whoever shows kindness to a household earns their reward.',
    { sort_order: 21, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'support-widow-monthly',
    7,
    8,
    'ادعم أرملة شهريًا',
    'Support a widow monthly',
    'الساعي على الأرملة كالساعي في سبيل الله.',
    'He who strives for a widow is like one striving in the cause of Allah.',
    { sort_order: 22, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'winter-clothing-drive',
    7,
    8,
    'حملة ملابس شتوية',
    'A winter clothing drive',
    'كسوةُ المؤمن تَقيهِ بردَ الدنيا والآخرة.',
    'Clothing the believer shields him from the cold of this world and the next.',
    { sort_order: 23, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'school-supplies-drive',
    7,
    8,
    'حملة مستلزمات مدرسية',
    'A school supplies drive',
    'العلمُ نورٌ، والقرطاسيةُ بابُ العلم.',
    'Knowledge is light; supplies are its gateway.',
    { sort_order: 24, difficulty_level: 2, xp_reward: 20 },
  ),
  d(
    'help-rebuild-damaged-home',
    7,
    8,
    'ساعد في إعادة بناء منزل متضرّر',
    'Help rebuild a damaged home',
    'ما بنى لله بيته إلا بنى اللهُ له بيتًا في الجنّة.',
    'Whoever builds a house for Allah, Allah builds him a house in Paradise.',
    { sort_order: 25, difficulty_level: 3, xp_reward: 30 },
  ),
  d(
    'fund-clean-water-access',
    7,
    8,
    'ادعم وصول ماء نظيف',
    'Fund clean water access',
    'خيرُ الصدقةِ سقياُ الماء.',
    'The best of charity is giving water to drink.',
    { sort_order: 26, difficulty_level: 3, xp_reward: 30 },
  ),
];

// ---------------------------------------------------------------------------
// Deed references (~30 total, spread across ≥ 15 deeds, mixing quran/hadith/athkar)
// Ordered by (deed_slug, sort_order). Idempotent in seed.ts via INSERT OR IGNORE
// on the (deed_id, source) unique index.
// ---------------------------------------------------------------------------

export const seedReferences: DeedReferenceRow[] = [
  // ---- smile-greet-stranger ----
  {
    deed_slug: 'smile-greet-stranger',
    type: 'hadith',
    text_ar: 'تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ',
    text_en: 'Your smile to your brother is charity.',
    source: 'Sunan al-Tirmidhi 1956',
    narrator: 'Abu Dharr (RA)',
    lesson_ar: 'أبسط عمل قد يكون أعظم الأجر عند الله.',
    lesson_en: 'The simplest act can carry the greatest reward with Allah.',
    sort_order: 1,
  },
  // ---- say-salam-first ----
  {
    deed_slug: 'say-salam-first',
    type: 'hadith',
    text_ar:
      'لَا تَدْخُلُونَ الْجَنَّةَ حَتَّى تُؤْمِنُوا، وَلَا تُؤْمِنُوا حَتَّى تَحَابُّوا، أَوَلَا أَدُلُّكُمْ عَلَى شَيْءٍ إِذَا فَعَلْتُمُوهُ تَحَابَبْتُمْ؟ أَفْشُوا السَّلَامَ بَيْنَكُمْ',
    text_en:
      'You will not enter Paradise until you believe, and you will not believe until you love one another. Shall I tell you of something which, if you do, you will love one another? Spread peace (salam) amongst yourselves.',
    source: 'Sahih Muslim 54',
    narrator: 'Abu Hurayrah (RA)',
    lesson_ar: 'إفشاء السلام بابٌ من أبواب الجنة.',
    lesson_en: 'Spreading salam is a door to Paradise.',
    sort_order: 1,
  },
  // ---- forgive-someone-today ----
  {
    deed_slug: 'forgive-someone-today',
    type: 'quran',
    text_ar:
      'وَجَزَاءُ سَيِّئَةٍ سَيِّئَةٌ مِّثْلُهَا ۖ فَمَنْ عَفَا وَأَصْلَحَ فَأَجْرُهُ عَلَى اللَّهِ',
    text_en:
      'The recompense for an injury is an injury equal to it, but whoever forgives and makes reconciliation, his reward is with Allah.',
    source: 'Surah Ash-Shura 42:40',
    narrator: null,
    lesson_ar: 'العفو بابٌ عظيم من أبواب الأجر.',
    lesson_en: 'Pardoning is a great door of reward.',
    sort_order: 1,
  },
  // ---- give-charity-today ----
  {
    deed_slug: 'give-charity-today',
    type: 'quran',
    text_ar:
      'مَّن ذَا الَّذِي يُقْرِضُ اللَّهَ قَرْضًا حَسَنًا فَيُضَاعِفَهُ لَهُ أَضْعَافًا كَثِيرَةً',
    text_en:
      'Who is it that will lend to Allah a goodly loan, so that He may multiply it for him many times over?',
    source: 'Surah Al-Baqarah 2:245',
    narrator: null,
    lesson_ar: 'كل ريال صدقة يعود أضعافًا.',
    lesson_en: 'Every riyal of charity returns many times over.',
    sort_order: 1,
  },
  {
    deed_slug: 'give-charity-today',
    type: 'quran',
    text_ar:
      'مَّن كَانَ يُرِيدُ حَرْثَ الْآخِرَةِ نَزِدْ لَهُ فِي حَرْثِهِ ۖ وَمَن كَانَ يُرِيدُ حَرْثَ الدُّنْيَا نُؤْتِهِ مِنْهَا',
    text_en:
      'Whoever desires the harvest of the Hereafter, We will increase for him his harvest; and whoever desires the harvest of this world, We will give him thereof.',
    source: 'Surah Ash-Shura 42:20',
    narrator: null,
    lesson_ar: 'الصدقةُ زراعةٌ للآخرة.',
    lesson_en: 'Charity is cultivation for the Hereafter.',
    sort_order: 2,
  },
  // ---- visit-sick-relative + visit-the-sick ----
  {
    deed_slug: 'visit-the-sick',
    type: 'hadith',
    text_ar:
      'خَمْسٌ مَنْ جَاءَ بِهِنَّ مَعَهُ يَوْمَ الْقِيَامَةِ ... وَعَادَ مَرِيضًا',
    text_en:
      'Five practices are of the fitrah: ... visiting the sick.',
    source: 'Sahih al-Bukhari 5400',
    narrator: 'Abu Hurayrah (RA)',
    lesson_ar: 'عيادةُ المريض من سنن الفطرة.',
    lesson_en: 'Visiting the sick is among the practices of fitrah.',
    sort_order: 1,
  },
  // ---- plant-a-tree ----
  {
    deed_slug: 'plant-a-tree',
    type: 'hadith',
    text_ar:
      'مَا مِنْ مُسْلِمٍ يَغْرِسُ غَرْسًا أَوْ يَزْرَعُ زَرْعًا فَيَأْكُلُ مِنْهُ طَيْرٌ أَوْ إِنْسَانٌ أَوْ بَهِيمَةٌ إِلَّا كَانَ لَهُ بِهِ صَدَقَةٌ',
    text_en:
      'No Muslim plants a tree or sows a crop, and then a bird, person, or animal eats from it, except that it is charity for him.',
    source: 'Sahih Muslim 1553',
    narrator: 'Jabir ibn Abdullah (RA)',
    lesson_ar: 'غِراسُك صدقةٌ لك ما دام يُنتفع به.',
    lesson_en: 'What you plant is charity as long as it benefits others.',
    sort_order: 1,
  },
  // ---- sponsor-orphan-monthly + sponsor-orphan-education ----
  {
    deed_slug: 'sponsor-orphan-monthly',
    type: 'hadith',
    text_ar:
      'أَنَا وَكَافِلُ الْيَتِيمِ فِي الْجَنَّةِ هَكَذَا',
    text_en: 'I and the guardian of an orphan will be in Paradise like this.',
    source: 'Sahih al-Bukhari 5304',
    narrator: 'Sahl ibn Sa\u2019d (RA)',
    lesson_ar: 'كفالةُ اليتيم قُربةٌ من النبيّ.',
    lesson_en: 'Sponsoring an orphan brings you close to the Prophet.',
    sort_order: 1,
  },
  {
    deed_slug: 'sponsor-orphan-education',
    type: 'quran',
    text_ar:
      'وَيُطْعِمُونَ الطَّعَامَ عَلَىٰ حُبِّهِ مِسْكِينًا وَيَتِيمًا وَأَسِيرًا',
    text_en:
      'And they give food, despite their love for it, to the poor, the orphan, and the captive.',
    source: 'Surah Al-Insan 76:8',
    narrator: null,
    lesson_ar: 'إطعامُ اليتيم من أعلام أهل الجنّة.',
    lesson_en: 'Feeding the orphan is a sign of the people of Paradise.',
    sort_order: 1,
  },
  // ---- remove-harm-from-path ----
  {
    deed_slug: 'remove-harm-from-path',
    type: 'hadith',
    text_ar:
      'الْإِيمَانُ بِضْعٌ وَسَبْعُونَ شُعْبَةً، فَأَفْضَلُهَا قَوْلُ لَا إِلَهَ إِلَّا اللَّهُ، وَأَدْنَاهَا إِمَاطَةُ الْأَذَى عَنِ الطَّرِيقِ',
    text_en:
      'Faith has seventy-odd branches; the highest is saying \u201cThere is no god but Allah,\u201d and the lowest is removing harm from the path.',
    source: 'Sahih al-Bukhari 9; Sahih Muslim 35',
    narrator: 'Abu Hurayrah (RA)',
    lesson_ar: 'إماطةُ الأذى من شعب الإيمان.',
    lesson_en: 'Removing harm from the path is a branch of faith.',
    sort_order: 1,
  },
  // ---- share-meal-with-neighbor / general ----
  {
    deed_slug: 'share-meal-with-neighbor',
    type: 'hadith',
    text_ar:
      'يَا أَبَا ذَرٍّ إِذَا طَبَخْتَ مَرَقَةً فَأَكْثِرْ مَاءَهَا، ثُمَّ تَحَرَّ أَهْلَ الْبَيْتِ مَنْ تَعْرِفُ',
    text_en:
      'O Abu Dharr, when you cook broth, add more water, then look after your neighbors.',
    source: 'Sahih Muslim 2625',
    narrator: 'Abu Dharr (RA)',
    lesson_ar: 'إكرامُ الجار من سنن المؤمن.',
    lesson_en: 'Honoring the neighbor is among the Sunnahs of the believer.',
    sort_order: 1,
  },
  // ---- reconcile-two-friends ----
  {
    deed_slug: 'reconcile-two-friends',
    type: 'hadith',
    text_ar:
      'أَلَا أُخْبِرُكُمْ بِأَفْضَلَ مِنْ دَرَجَةِ الصِّيَامِ وَالصَّلَاةِ وَالصَّدَقَةِ؟ قَالُوا: بَلَى. قَالَ: إِصْلَاحُ ذَاتِ الْبَيْنِ',
    text_en:
      'Shall I not tell you of something better in degree than fasting, prayer, and charity? They said: Of course. He said: Making peace between people.',
    source: 'Sunan Abu Dawud 4919; Sunan al-Tirmidhi 2509',
    narrator: 'Abu Ayyub al-Ansari (RA)',
    lesson_ar: 'الإصلاح بين الناس من أفضل الأعمال.',
    lesson_en: 'Reconciliation between people is among the best deeds.',
    sort_order: 1,
  },
  // ---- feed-stray-cat (kindness to animals) ----
  {
    deed_slug: 'feed-stray-cat',
    type: 'hadith',
    text_ar:
      'دَخَلَتِ امْرَأَةٌ النَّارَ فِي هِرَّةٍ رَبَطَتْهَا فَلَمْ تُطْعِمْهَا وَلَمْ تَدَعْهَا تَأْكُلُ مِنْ خَشَاشِ الْأَرْضِ',
    text_en:
      'A woman entered Hell because of a cat she had confined, neither feeding it nor letting it eat from the insects of the earth.',
    source: 'Sahih al-Bukhari 3140; Sahih Muslim 2242',
    narrator: 'Abdullah ibn Umar (RA)',
    lesson_ar: 'الرفق بالحيوان واجبٌ شرعي.',
    lesson_en: 'Kindness to animals is a religious duty.',
    sort_order: 1,
  },
  {
    deed_slug: 'feed-stray-cat',
    type: 'hadith',
    text_ar:
      'فِي كُلِّ كَبِدٍ رَطْبَةٍ أَجْرٌ',
    text_en: 'In every moist liver (living creature) there is a reward.',
    source: 'Sahih Muslim 2244',
    narrator: 'Abu Hurayrah (RA)',
    lesson_ar: 'إطعامُ حيوانٍ أجرٌ دائم.',
    lesson_en: 'Feeding an animal is an ongoing reward.',
    sort_order: 2,
  },
  // ---- dua-for-parents ----
  {
    deed_slug: 'dua-for-parents',
    type: 'quran',
    text_ar:
      'وَقُل رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    text_en:
      'And say, \u201cMy Lord, have mercy on them as they brought me up when I was small.\u201d',
    source: 'Surah Al-Isra 17:24',
    narrator: null,
    lesson_ar: 'الرحمةُ بالوالدين دعوةٌ مأجورة.',
    lesson_en: 'Mercy to parents is a rewarded dua.',
    sort_order: 1,
  },
  // ---- teach-someone-quran ----
  {
    deed_slug: 'teach-someone-quran',
    type: 'hadith',
    text_ar:
      'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
    text_en: 'The best of you are those who learn the Quran and teach it.',
    source: 'Sahih al-Bukhari 5027',
    narrator: 'Uthman ibn Affan (RA)',
    lesson_ar: 'تعليمُ القرآن من علامات الخير.',
    lesson_en: 'Teaching the Quran is a sign of goodness.',
    sort_order: 1,
  },
  // ---- morning athkar (linked to recite-morning-adhkar via hint; attach to a real slug) ----
  // We don't have a dedicated morning-athkar deed; attach athkar to "dua-for-someone-absent"
  // (which is closest semantically — remembrance-based deed) plus "salam-to-family".
  {
    deed_slug: 'dua-for-someone-absent',
    type: 'athkar',
    text_ar:
      'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ',
    text_en:
      'O Allah, I ask You for pardon and well-being in this world and the Hereafter.',
    source: 'Sunan Ibn Majah 3871 (morning/evening)',
    narrator: 'Abdullah ibn Umar (RA)',
    lesson_ar: 'العافيةُ أثمنُ ما يُطلب من الله.',
    lesson_en: 'Well-being is the most precious thing to ask Allah for.',
    sort_order: 1,
  },
  {
    deed_slug: 'salam-to-family',
    type: 'athkar',
    text_ar:
      'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    text_en:
      'In the name of Allah, with whose name nothing can harm on earth or in the heavens, and He is the All-Hearing, the All-Knowing.',
    source: 'Sunan Abu Dawud 5088 (morning/evening)',
    narrator: 'Uthman ibn Affan (RA)',
    lesson_ar: 'الأذكارُ حصنٌ من كل سوء.',
    lesson_en: 'Remembrances are a shield from every harm.',
    sort_order: 1,
  },
  // ---- forgive-family-member ----
  {
    deed_slug: 'forgive-family-member',
    type: 'quran',
    text_ar:
      'خُذِ الْعَفْوَ وَأْمُرْ بِالْعُرْفِ وَأَعْرِضْ عَنِ الْجَاهِلِينَ',
    text_en:
      'Show forgiveness, enjoin what is good, and turn away from the ignorant.',
    source: 'Surah Al-A\u2019raf 7:199',
    narrator: null,
    lesson_ar: 'العفو من أخلاق المؤمنين.',
    lesson_en: 'Pardoning is among the manners of the believers.',
    sort_order: 1,
  },
  // ---- kind-words-to-spouse ----
  {
    deed_slug: 'kind-words-to-spouse',
    type: 'quran',
    text_ar:
      'وَلَا تَسْتَوِي الْحَسَنَةُ وَلَا السَّيِّئَةُ ۚ ادْفَعْ بِالَّتِي هِيَ أَحْسَنُ فَإِذَا الَّذِي بَيْنَكَ وَبَيْنَهُ عَدَاوَةٌ كَأَنَّهُ وَلِيٌّ حَمِيمٌ',
    text_en:
      'Good and evil are not equal. Repel evil with what is better, and you will see that the one who was your enemy has become your close friend.',
    source: 'Surah Fussilat 41:34',
    narrator: null,
    lesson_ar: 'الكلمة الحسنة تُحوّل العداوة إلى ودٍّ.',
    lesson_en: 'A kind word turns enmity into affection.',
    sort_order: 1,
  },
  // ---- donate-blood ----
  {
    deed_slug: 'donate-blood',
    type: 'quran',
    text_ar:
      'وَمَنْ أَحْسَنُ قَوْلًا مِّمَّن دَعَا إِلَى اللَّهِ وَعَمِلَ صَالِحًا وَقَالَ إِنَّنِي مِنَ الْمُسْلِمِينَ',
    text_en:
      'And who is better in speech than one who calls to Allah and does righteousness and says, \u201cIndeed, I am of the Muslims\u201d?',
    source: 'Surah Fussilat 41:33',
    narrator: null,
    lesson_ar: 'العملُ الصالح صورةٌ من دعوة الحقّ.',
    lesson_en: 'Righteous action is a form of calling to truth.',
    sort_order: 1,
  },
  // ---- give-water-to-traveler ----
  {
    deed_slug: 'give-water-to-traveler',
    type: 'hadith',
    text_ar:
      'سَابِقُوا إِلَى مَغْفِرَةٍ مِّن رَّبِّكُمْ',
    text_en: 'Race to forgiveness from your Lord.',
    source: 'Surah Al-Hadid 57:21',
    narrator: null,
    lesson_ar: 'بادرْ بالأجر قبل فواته.',
    lesson_en: 'Race for reward before it slips away.',
    sort_order: 1,
  },
  // ---- help-pay-debt ----
  {
    deed_slug: 'help-pay-debt',
    type: 'hadith',
    text_ar:
      'مَنْ فَكَّ كُرْبَةً مِنْ كُرَبِ الدُّنْيَا فَكَّ اللَّهُ عَنْهُ كُرْبَةً مِنْ كُرَبِ يَوْمِ الْقِيَامَةِ',
    text_en:
      'Whoever relieves a hardship of this world for a believer, Allah will relieve a hardship of the Day of Judgment for him.',
    source: 'Sahih Muslim 2699',
    narrator: 'Abu Hurayrah (RA)',
    lesson_ar: 'تفريجُ الكُرب أثقلُ في الميزان.',
    lesson_en: 'Relieving distress is heaviest on the scale.',
    sort_order: 1,
  },
  // ---- pay-zakat-today ----
  {
    deed_slug: 'pay-zakat-today',
    type: 'quran',
    text_ar:
      'خُذْ مِنْ أَمْوَالِهِمْ صَدَقَةً تُطَهِّرُهُمْ وَتُزَكِّيهِمْ بِهَا',
    text_en:
      'Take from their wealth a charity by which you purify them and cause them to increase.',
    source: 'Surah Al-Tawbah 9:103',
    narrator: null,
    lesson_ar: 'الزكاةُ تزكيةٌ للمال والنفس.',
    lesson_en: 'Zakat purifies wealth and the soul.',
    sort_order: 1,
  },
  // ---- cover-colleague-lunch (feeding others) ----
  {
    deed_slug: 'cover-colleague-lunch',
    type: 'quran',
    text_ar:
      'وَيُطْعِمُونَ الطَّعَامَ عَلَىٰ حُبِّهِ مِسْكِينًا وَيَتِيمًا وَأَسِيرًا',
    text_en:
      'And they give food, despite their love for it, to the poor, the orphan, and the captive.',
    source: 'Surah Al-Insan 76:8',
    narrator: null,
    lesson_ar: 'إطعامُ الطعام من أخلاق المتّقين.',
    lesson_en: 'Feeding others is among the manners of the God-conscious.',
    sort_order: 1,
  },
  // ---- be-kind-to-animals via water for birds ----
  {
    deed_slug: 'provide-water-for-bird',
    type: 'hadith',
    text_ar:
      'بَيْنَمَا رَجُلٌ يَمْشِي بِطَرِيقٍ اشْتَدَّ عَلَيْهِ الْعَطَشُ، فَوَجَدَ بِئْرًا فَنَزَلَ فِيهَا فَشَرِبَ، ثُمَّ خَرَجَ فَإِذَا كَلْبٌ يَلْهَثُ يَأْكُلُ الثَّرَى مِنَ الْعَطَشِ، فَقَالَ: لَقَدْ بَلَغَ هَذَا مِثْلُ الَّذِي بَلَغَ بِي، فَمَلَأَ خُفَّهُ مَاءً ... فَشَكَرَ اللَّهُ لَهُ فَغَفَرَ لَهُ',
    text_en:
      'A man was walking on a road and became very thirsty. He found a well and drank from it. He then saw a dog panting and eating dirt from thirst. He said, \u201cThis dog has reached the same level of thirst I had.\u201d He filled his shoe with water, gave it to the dog, and Allah thanked him and forgave him.',
    source: 'Sahih al-Bukhari 2466; Sahih Muslim 2244',
    narrator: 'Abu Hurayrah (RA)',
    lesson_ar: 'الرحمةُ بالحيوان بابٌ للمغفرة.',
    lesson_en: 'Mercy to animals is a door to forgiveness.',
    sort_order: 1,
  },
  // ---- call-parent-today ----
  {
    deed_slug: 'call-parent-today',
    type: 'quran',
    text_ar:
      'وَبِالْوَالِدَيْنِ إِحْسَانًا',
    text_en: 'And [commanded] be good to parents.',
    source: 'Surah Al-Isra 17:23',
    narrator: null,
    lesson_ar: 'الإحسانُ للوالدين فريضةٌ عظيمة.',
    lesson_en: 'Being good to parents is a great obligation.',
    sort_order: 1,
  },
  // ---- send-gift-to-cousin ----
  {
    deed_slug: 'send-gift-to-cousin',
    type: 'hadith',
    text_ar:
      'تَهَادُوا تَحَابُّوا',
    text_en: 'Give gifts to one another and you will love one another.',
    source: 'Sahih al-Bukhari 5442 (Mu\u2019adh ibn Jabal)',
    narrator: 'Mu\u2019adh ibn Jabal (RA)',
    lesson_ar: 'الهديةُ تُحيي المودّة.',
    lesson_en: 'Gifts revive affection.',
    sort_order: 1,
  },
  // ---- words-of-consolation (athkar context) ----
  {
    deed_slug: 'words-of-consolation',
    type: 'athkar',
    text_ar:
      'إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ، اللَّهُمَّ أَجِرْنِي فِي مُصِيبَتِي وَأَخْلِفْ لِي خَيْرًا مِنْهَا',
    text_en:
      'Indeed, to Allah we belong and to Him we shall return. O Allah, reward me in my affliction and replace it with something better.',
    source: 'Sahih Muslim 918',
    narrator: 'Umm Salamah (RA)',
    lesson_ar: 'الاسترجاعُ بابٌ للتخفيف والأجر.',
    lesson_en: 'Saying \u201cTo Allah we belong\u201d is a door to relief.',
    sort_order: 1,
  },
];
